In [75]:
from pathlib import Path
import pandas as pd

In [76]:
# project root 
parent_root = Path.cwd()

# data directories
raw_data = parent_root/"data"

# reports
reports = parent_root.mkdir(parents=True, exist_ok=True)

In [77]:
# importing data
schools = pd.read_csv(raw_data/'schools.csv')
baseline = pd.read_csv(raw_data/'Baseline_Survey.csv')
prefill = pd.read_csv(raw_data/'prefilling_data.csv')
endline = pd.read_csv(raw_data/'Endline_Survey.csv')

In [78]:
# checking for missing pages
endline.head()

,#,Pages,Uploaded (UTC),Link,Notes,Filename(s),Version,Student Name,Admission number,Shamiri ID,...,10. The sessions made me think about my own life in a useful way.,11. The sessions gave me ideas for handling challenges in my life.,12. I used something from the sessions outside the group.,13. I found the sessions useful.,14. I would recommend these sessions to another student.,15. I knew how to ask for extra support if I needed it.,What was the most useful thing you learned or practiced in the sessions?,What should be changed to make the sessions better for students?,Print Batch Nº,Tag
0,IIV_1,7,13/08/2026 12:33:10,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,OTIENOOYOOSECONDARY_OOS_7_0001.pdf,#3 XWEK,Dancan Zakayo,11895,NaN,...,C. Not sure,B. Disagree,E. Strongly agree,D. Agree,E. Strongly agree,E. Strongly agree,I learnt problem solving skills,NaN,IIV_ON7I,NaN
1,IIV_2,7,13/08/2026 12:32:54,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,OTIENOOYOOSECONDARY_OOS_7_0001.pdf,#3 XWEK,Mourice Amenya,11830,NaN,...,D. Agree,E. Strongly agree,D. Agree,D. Agree,D. Agree,C. Not sure,I learnt to be gracious and practice makes per...,The way we are distributed in groups should be...,IIV_ON7I,NaN
2,NV4_32,7,29/07/2026 08:35:12,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,STIGNATIUSLOYOLAMAGADISECONDARYSCHOOL_SILMS_18...,#3 XWEK,Newton Ochieng,5358,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,I learnt that we should be greatful and thankf...,'- there should be brought advices also conser...,NV4_PEYF,NaN
3,NV4_33,7,29/07/2026 08:34:51,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,STIGNATIUSLOYOLAMAGADISECONDARYSCHOOL_SILMS_21...,#3 XWEK,Esther Nuru,5495,NaN,...,E. Strongly agree,E. Strongly agree,D. Agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,• I have learn how to deal with challenges • B...,Doing things practicle. Playing games to make ...,NV4_PEYF,NaN
4,NV4_34,7,29/07/2026 08:34:28,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,STIGNATIUSLOYOLAMAGADISECONDARYSCHOOL_SILMS_21...,#3 XWEK,Valentine Atieno,5301,NaN,...,E. Strongly agree,E. Strongly agree,D. Agree,D. Agree,D. Agree,E. Strongly agree,To always speak out your mind and avoid peer p...,By increasing more time for the Session to Stu...,NV4_PEYF,NaN

In [79]:
# 1. missing pages
baseline_missing = baseline[baseline['Pages'] < 10].copy()
endline_missing = endline[endline['Pages'] < 7].copy()
# endline_missing

In [80]:
endline.columns.tolist()

['#',
 'Pages',
 'Uploaded (UTC)',
 'Link',
 'Notes',
 'Filename(s)',
 'Version',
 'Student Name',
 'Admission number',
 'Shamiri ID',
 'School Name',
 'School ID',
 'What class are you in?',
 'Stream',
 "Today's Date",
 'Supervisor name',
 'Supervisor name.1',
 'Supervisor name.2',
 'Group Leader Name',
 'Group Number',
 'Unnamed: 20',
 "1. Over the last two weeks, I've been feeling hopeful about the future.",
 "2. Over the last two weeks, I've been feeling useful.",
 "3. Over the last two weeks, I've been feeling relaxed.",
 "4. Over the last two weeks, I've been dealing with problems well.",
 "5. Over the last two weeks, I've been thinking clearly.",
 "6. Over the last two weeks, I've been feeling close to other people.",
 "7.  Over the last two weeks, I've been able to make up my own mind about things.",
 'Unnamed: 28',
 '1. Little interest or pleasure in doing things?',
 '2. Feeling sad, depressed or hopeless?',
 '3. Trouble falling or staying asleep, or sleeping too much?',
 '4. Feeling tired or having little energy?',
 '5. Poor appetite or eating too much (overeating)?',
 '6. Feeling bad about yourself – or that you are a failure or have let yourself or your family down?',
 '7. Trouble concentrating on things, such as reading a book?',
 '8. Moving or speaking so slowly that other people could have noticed. Or the opposite — being so energetic or nervous that you have been moving around a lot more than usual?',
 'If you have experienced any of the problems listed above, how difficult have they made it for you to do your work or get along with other people?',
 'Unnamed: 38',
 '1. Feeling nervous, anxious, restless, or uneasy?',
 '2. Not being able to stop or control worrying about things?',
 '3. Worrying too much about different things?',
 '4. Trouble relaxing?',
 "5. Being so restless or uneasy that it's hard to sit still?",
 '6. Becoming easily annoyed or irritable?',
 '7. Feeling afraid as if something bad might happen?',
 '8. If you read this question, respond "Not at all”.',
 'If you have experienced any of the problems listed above, how difficult have they made it for you to do your work or get along with other people?.1',
 'Unnamed: 48',
 '1. When I am sad, I think about how alone I feel.',
 '2. When I am sad, I go away by myself and think about why I feel this way.',
 '3. When I am sad, I think: “I’m ruining everything”.',
 '4. When I am sad, I think about how sad I feel.',
 '5. When I am sad, I go someplace alone to think about my feelings.',
 '6. When I am sad, I think about how angry I am with myself.',
 '7. When I am sad, I think about other times when I have felt sad.',
 '8. When I am sad, I think about a recent situation wishing it had gone better.',
 '9. When I am sad, I think: “There must be something wrong with me or I wouldn’t feel this way”.',
 '10. When I am sad, I think: “I’m disappointing my friends, family, or teachers”.',
 '11. When I am sad, I think about all my failures, faults, and mistakes.',
 '12. When I am sad, I think: “Why can’t I handle things better?"',
 "13. When I am sad, I think about how I don't feel like doing anything.",
 'Unnamed: 62',
 '1. Teachers and staff seem to take a real interest in my future.',
 '2. Teachers are available when I need to talk with them.',
 '3. It is easy to talk with teachers.',
 '4. Students get along well with teachers.',
 '5. Teachers at my school help us children with our problems.',
 '6. My teachers care about me.',
 '7. My teacher makes me feel good about myself.',
 '8. Students have same opportunity in class to speak, and be listened to, in class.',
 '9. Students can express feelings and thoughts about school work and life.',
 '10. Students "different" in any way are treated with respect.',
 '11. Nobody in my school is excluded from being successful.',
 '12. Females and males treated as equals at school.',
 '13. I can participate in a lot of interesting activities at school.',
 '14. My schoolwork is exciting.',
 '15. Students can make suggestions on courses that are offered.',
 '16. This school make student enthusiastic about learning.',
 '17. Students are frequently rewarded or praised by faculty and staff for following school rules.',
 '18. I am happy with the kinds of students who go to my school.',
 '19. I am happy, in general, with the other students who go to my school.',
 '20. I am happy about the number of tests.',
 '21. I am happy about the amount of homework I have.',
 'Unnamed: 84',
 '1. I follow the rules at school.',
 '2. I get in trouble at school.',
 '3. When I am in class, I just act as if I am working.',
 '4. I pay attention in class.',
 '5. I complete my work on time.',
 '6. I like being at school.',
 '7.I feel excited by my work at school.',
 '8. My classroom is a fun place to be.',
 '9. I am interested in the work at school.',
 '10. I feel happy in school.',
 '11. I feel bored in school.',
 '12. I check my schoolwork for mistakes.',
 "13. I study at home even when I don't have a test.",
 '14. I try to watch TV shows about things we do in school.',
 '15.When I read a book, I ask myself questions to make sure I understand what it is about.',
 '16.I read extra books to learn more about things we do in school.',
 "17. If I don't know what a word means when I am reading, I do something to figure it out.",
 "18.If I don't understand what I read, I go back and read it over again.",
 '19.I talk with people outside of school about what I am learning in class.',
 'Unnamed: 104',
 '1. I get very angry.',
 "2. I usually do as I'm told.",
 '3. I fight a lot.',
 '4. I am often accused of lying or cheating.',
 '5.  I take things that are not mine.',
 '6. I am restless.',
 '7. I am constantly fidgeting.',
 '8. I am easily distracted.',
 '9. I think before I do things.',
 '10. I finish the work I am doing.',
 'Rate how much you agree or disagree with the following statements, thinking about the Shamiri program and the sessions as a whole.',
 '1. I felt comfortable being part of my group.',
 '2. Students in my group listened to each other respectfully.',
 '3. I felt safe sharing my thoughts during the sessions.',
 '4. I felt respected by the group leader.',
 '5. The group leader explained the activities clearly.',
 '6. I understood why we were doing the session activities.',
 '7. I participated in the session activities.',
 '8. I completed the reflection or written activities during the sessions.',
 '9. I tried the take-home or home practice activities between sessions.',
 '10. The sessions made me think about my own life in a useful way.',
 '11. The sessions gave me ideas for handling challenges in my life.',
 '12. I used something from the sessions outside the group.',
 '13. I found the sessions useful.',
 '14. I would recommend these sessions to another student.',
 '15. I knew how to ask for extra support if I needed it.',
 'What was the most useful thing you learned or practiced in the sessions?',
 'What should be changed to make the sessions better for students?',
 'Print Batch Nº',
 'Tag']

In [94]:
# 2. school name mismatch
reference_schools = schools['School Name']
baseline_name_mismatch = baseline[
    ~baseline["School Name"].isin(reference_schools)
].copy()

endline_name_mismatches = endline[
    ~endline['School Name'].isin(reference_schools)
].copy()
endline_name_mismatches

,#,Pages,Uploaded (UTC),Link,Notes,Filename(s),Version,Student Name,Admission number,Shamiri ID,...,10. The sessions made me think about my own life in a useful way.,11. The sessions gave me ideas for handling challenges in my life.,12. I used something from the sessions outside the group.,13. I found the sessions useful.,14. I would recommend these sessions to another student.,15. I knew how to ask for extra support if I needed it.,What was the most useful thing you learned or practiced in the sessions?,What should be changed to make the sessions better for students?,Print Batch Nº,Tag
286,BPZ_11,7,08/07/2026 15:32:42,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_24_0001.pdf,#3 XWEK,Monte Amondi,7952,NaN,...,E. Strongly agree,E. Strongly agree,D. Agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,• Ive learnt that we should not suffer in sile...,"• For me, the session is as good as it is thou...",BPZ_F5EG,NaN
287,BPZ_24,7,08/07/2026 15:32:40,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_29_0001.pdf,#3 XWEK,Elizabeth Achieng,7986,NaN,...,E. Strongly agree,E. Strongly agree,A. Strongly disagree,E. Strongly agree,E. Strongly agree,E. Strongly agree,Most useful thing I have learned in the sessio...,They should extend time for more understandmen...,BPZ_F5EG,NaN
288,BPZ_15,7,08/07/2026 15:32:39,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_26_0001.pdf,#3 XWEK,Fidel Odongo,8030,NaN,...,D. Agree,D. Agree,C. Not sure,E. Strongly agree,E. Strongly agree,C. Not sure,"I learnt that, we as learners who should know ...",None of all should not be changed in the sessi...,BPZ_F5EG,NaN
290,BPZ_13,7,08/07/2026 15:32:31,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_25_0001.pdf,#3 XWEK,Fabrian Otieno,8147,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,'-Teamwork is importance to learner becaus it ...,Nothing.,BPZ_F5EG,NaN
292,BPZ_12,7,08/07/2026 15:32:18,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_24_0001.pdf,#3 XWEK,Grace Adhiambo,7812,NaN,...,D. Agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,D. Agree,The problem-solving framework because it has h...,During the session you should implement some g...,BPZ_F5EG,NaN
294,BPZ_23,7,08/07/2026 15:32:12,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_29_0001.pdf,#3 XWEK,Ida Akinyi Odhiambo,7907,NaN,...,E. Strongly agree,E. Strongly agree,D. Agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,Steps for solving life's problems. Gratitude V...,More time should be added for we enjoy and lea...,BPZ_F5EG,NaN
295,BPZ_16,7,08/07/2026 15:32:12,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_26_0001.pdf,#3 XWEK,Elvis Otieno,7916,NaN,...,E. Strongly agree,E. Strongly agree,D. Agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,I learned that practice make better. when you ...,Nothing should be changed to the sessions.,BPZ_F5EG,NaN
296,BPZ_14,7,08/07/2026 15:32:05,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_25_0001.pdf,#3 XWEK,Ishmael Ochieng,7947,NaN,...,D. Agree,E. Strongly agree,E. Strongly agree,D. Agree,D. Agree,D. Agree,I practised to be responsible person when I am...,for being responsible all of the time,BPZ_F5EG,NaN
297,BPZ_9,7,08/07/2026 15:31:52,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_23_0001.pdf,#3 XWEK,Benjamin Benoni,8251,NaN,...,D. Agree,D. Agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,"Neuroplasticity, thoughts and values",NaN,BPZ_F5EG,NaN
298,BPZ_54,7,08/07/2026 15:31:51,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_22_0001.pdf,#3 XWEK,Juliet Andeyo,7798,NaN,...,E. Strongly agree,D. Agree,E. Strongly agree,D. Agree,D. Agree,E. Strongly agree,It is important to have values in your life as...,Using digital divice to learn,BPZ_F5EG,NaN
300,BPZ_49,7,08/07/2026 15:31:47,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_17_0001.pdf,#3 XWEK,John Mark,7830,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,Problem solving,Something like a reward or gifts or something ...,BPZ_F5EG,NaN
301,BPZ_2,7,08/07/2026 15:31:45,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_30_0001.pdf,#3 XWEK,Rooney Awili Onyango,8041,NaN,...,D. Agree,D. Agree,E. Strongly agree,D. Agree,C. Not sure,E. Strongly agree,To fear others. To steel our class mates.,How to solve challanges. to respect others.,BPZ_F5EG,NaN
302,BPZ_31,7,08/07/2026 15:31:44,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_2_0001.pdf,#3 XWEK,Michael Odhiambo,8245,NaN,...,E. Strongly agree,C. Not sure,D. Agree,E. Strongly agree,E. Strongly agree,D. Agree,gratitude,NaN,BPZ_F5EG,NaN
303,BPZ_7,7,08/07/2026 15:31:39,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_18_0001.pdf,#3 XWEK,Fred Odiwuor,7865,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,The session helped me to know how to handle my...,The session should not have any an end because...,BPZ_F5EG,NaN
304,BPZ_3,7,08/07/2026 15:31:36,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_20_0001.pdf,#3 XWEK,Lennox Lewis,8144,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BPZ_F5EG,NaN
307,BPZ_10,7,08/07/2026 15:31:22,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_23_0001.pdf,#3 XWEK,Calvin Okoth,7968,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,Neuroplasticity About how to develop brain,Nothing should be changed but my group leader ...,BPZ_F5EG,NaN
308,BPZ_53,7,08/07/2026 15:31:18,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_22_0001.pdf,#3 XWEK,Mary Hazel Akoth,8064,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,D. Agree,E. Strongly agree,E. Strongly agree,It is important to know our life values,More booklets Time for arrival,BPZ_F5EG,NaN
310,BPZ_50,7,08/07/2026 15:31:14,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_17_0001.pdf,#3 XWEK,Charles Okoth,7810,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,Grattitude,The session should be brought even during the ...,BPZ_F5EG,NaN
311,BPZ_1,7,08/07/2026 15:31:12,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_30_0001.pdf,#3 XWEK,Brighton Otieno,8175,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BPZ_F5EG,NaN
312,BPZ_8,7,08/07/2026 15:31:07,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_18_0001.pdf,#3 XWEK,Michael Ochieng Mboya,7946,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,How to Cope up with different Situations on my...,What Should be Changed is the time. The time i...,BPZ_F5EG,NaN
313,BPZ_32,7,08/07/2026 15:31:06,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_2_0001.pdf,#3 XWEK,Fidel Atena,8151,NaN,...,E. Strongly agree,D. Agree,E. Strongly agree,D. Agree,E. Strongly agree,D. Agree,'-What was useful things that we learned in th...,We should be confident,BPZ_F5EG,NaN
314,BPZ_4,7,08/07/2026 15:31:04,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_20_0001.pdf,#3 XWEK,Daniel Amollo,8210,NaN,...,E. Strongly agree,D. Agree,B. Disagree,E. Strongly agree,E. Strongly agree,E. Strongly agree,How to handle risk things and to be confident.,It should be kept frequently,BPZ_F5EG,NaN
318,BPZ_55,7,08/07/2026 15:30:38,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_5_0001.pdf,#3 XWEK,Byron Odhiambo,7836,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,D. Agree,'- I learnt that everything is possible also w...,I suggest that next time their should be some ...,BPZ_F5EG,NaN
320,BPZ_26,7,08/07/2026 15:30:35,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_1_0001.pdf,#3 XWEK,Sarah Windley,7888,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,B. Disagree,E. Strongly agree,E. Strongly agree,Things are good Like to handle challages alone,Nothing should be changed,BPZ_F5EG,NaN
323,BPZ_6,7,08/07/2026 15:30:29,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_21_0001.pdf,#3 XWEK,Lavenda Adhiambo,7908,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BPZ_F5EG,NaN
329,BPZ_25,7,08/07/2026 15:30:04,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_1_0001.pdf,#3 XWEK,Bravinsencia Anyango,7976,NaN,...,D. Agree,E. Strongly agree,C. Not sure,D. Agree,D. Agree,E. Strongly agree,I learn how I can handle my challanges in life.,By not speaking to students rudely. Being open...,BPZ_F5EG,NaN
330,BPZ_45,7,08/07/2026 15:30:03,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_12_0001.pdf,#3 XWEK,Gladys Akinyi,7901,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BPZ_F5EG,NaN
332,BPZ_56,7,08/07/2026 15:30:00,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_5_0001.pdf,#3 XWEK,Josephat Samuel,7925,NaN,...,E. Strongly agree,D. Agree,C. Not sure,D. Agree,E. Strongly agree,E. Strongly agree,'- To share our thought with trusted people - ...,'- They must change the time for example Once ...,BPZ_F5EG,NaN
334,BPZ_5,7,08/07/2026 15:29:57,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_21_0001.pdf,#3 XWEK,Ayodo Haidama Atieno,8124,NaN,...,D. Agree,E. Strongly agree,A. Strongly disagree,E. Strongly agree,E. Strongly agree,D. Agree,Ways of solving problems on your own. Ways of ...,They should give out rewards to motivate stude...,BPZ_F5EG,NaN
340,BPZ_46,7,08/07/2026 15:29:29,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_12_0001.pdf,#3 XWEK,Mercy Mitchelle,7809,NaN,...,D. Agree,D. Agree,C. Not sure,C. Not sure,C. Not sure,D. Agree,I felt comfortable being part of my group The ...,Keaping time Answering quesions when the quest...,BPZ_F5EG,NaN
346,BPZ_35,7,08/07/2026 15:29:10,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_14_0001.pdf,#3 XWEK,Charles Ochieng,8166,NaN,...,D. Agree,D. Agree,D. Agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,1. How to solv a problem. 11. How to have grat...,1. Nothing.,BPZ_F5EG,NaN
352,BPZ_34,7,08/07/2026 15:28:45,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_13_0001.pdf,#3 XWEK,Henry Onyango,7803,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,Humility.,Number of times that you're coming.,BPZ_F5EG,NaN
357,BPZ_36,7,08/07/2026 15:28:33,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_14_0001.pdf,#3 XWEK,Paul Otieno,8241,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BPZ_F5EG,NaN
362,BPZ_33,7,08/07/2026 15:28:06,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_13_0001.pdf,#3 XWEK,Wicklif Onyango Otieno,7808,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,Wisdom,Nothing,BPZ_F5EG,NaN
365,BPZ_41,7,08/07/2026 15:27:47,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_11_0001.pdf,#3 XWEK,Benson Wachira,8103,NaN,...,D. Agree,E. Strongly agree,D. Agree,D. Agree,D. Agree,E. Strongly agree,I learned how to cope and deal with challenges...,The time the shamiri offers is a bit little fo...,BPZ_F5EG,NaN
373,BPZ_27,7,08/07/2026 15:27:29,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_10_0001.pdf,#3 XWEK,kevin ochieng,7959,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,I practised how I can interact with people in ...,By engaging other students from different scho...,BPZ_F5EG,NaN
376,BPZ_42,7,08/07/2026 15:27:11,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_11_0001.pdf,#3 XWEK,Brandon Peter,8102,NaN,...,E. Strongly agree,E. Strongly agree,D. Agree,E. Strongly agree,E. Strongly agree,D. Agree,Value The values I learnt from the session can...,Nothing.,BPZ_F5EG,NaN
385,BPZ_28,7,08/07/2026 15:26:53,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_10_0001.pdf,#3 XWEK,Boron Barack Otieno,8234,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BPZ_F5EG,NaN
389,BPZ_48,7,08/07/2026 15:26:25,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_9_0001.pdf,#3 XWEK,Tabitha Aumah Nyawir,8055,NaN,...,E. Strongly agree,D. Agree,D. Agree,E. Strongly agree,E. Strongly agree,A. Strongly disagree,What i shared was to remain secret which impre...,They Should Continue Keeping secrets by not vi...,BPZ_F5EG,NaN
391,BPZ_17,7,08/07/2026 15:26:22,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_19_0001.pdf,#3 XWEK,Deryl M Oduor,8235,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,This session of Shamiri have help me to grow m...,'-The Shamiri Organisation should be giving aw...,BPZ_F5EG,NaN
392,BPZ_20,7,08/07/2026 15:26:19,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_27_0001.pdf,#3 XWEK,Ondiek Emelda,7841,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BPZ_F5EG,NaN
393,BPZ_52,7,08/07/2026 15:26:16,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_16_0001.pdf,#3 XWEK,Irine Akoth,7906,NaN,...,E. Strongly agree,E. Strongly agree,D. Agree,E. Strongly agree,E. Strongly agree,D. Agree,• Gratitude -> I learnt that I should be great...,• They should provide adiquet resources. • The...,BPZ_F5EG,NaN
395,BPZ_37,7,08/07/2026 15:26:14,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_3_0001.pdf,#3 XWEK,Sharon Atieno,8190,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BPZ_F5EG,NaN
397,BPZ_44,7,08/07/2026 15:26:09,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_8_0001.pdf,#3 XWEK,Marion Anyango,7895,NaN,...,D. Agree,D. Agree,C. Not sure,C. Not sure,C. Not sure,C. Not sure,I learnt how to bild a healthy relashionship.,To respect each other to bilnd a good relashio...,BPZ_F5EG,NaN
401,BPZ_47,7,08/07/2026 15:25:49,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_9_0001.pdf,#3 XWEK,Lucy Bokita,7929,NaN,...,D. Agree,D. Agree,B. Disagree,D. Agree,E. Strongly agree,D. Agree,I usefully learn how to manage my emotion & In...,Clear understandably of challenges the faced a...,BPZ_F5EG,NaN
403,BPZ_19,7,08/07/2026 15:25:44,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_27_0001.pdf,#3 XWEK,Mitchelle Achieng,8054,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BPZ_F5EG,NaN
404,BPZ_18,7,08/07/2026 15:25:43,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_19_0001.pdf,#3 XWEK,Onditi Isaiah,8233,NaN,...,D. Agree,D. Agree,D. Agree,D. Agree,D. Agree,D. Agree,'-This sesion have made me know how to interac...,'-Providing a rewards -Giving people hope for ...,BPZ_F5EG,NaN
405,BPZ_38,7,08/07/2026 15:25:38,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_3_0001.pdf,#3 XWEK,Catherine Awuor,7870,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,by practicing good qualities by showing gratitude,Consalting them daily having discussion on the...,BPZ_F5EG,NaN
407,BPZ_51,7,08/07/2026 15:25:37,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_16_0001.pdf,#3 XWEK,Sharon Shambua,7825,NaN,...,E. Strongly agree,E. Strongly agree,D. Agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,We should be greatful for things that are good...,They should come everyweek not only for four w...,BPZ_F5EG,NaN
409,BPZ_43,7,08/07/2026 15:25:32,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_8_0001.pdf,#3 XWEK,Mitchell Hawi,8201,NaN,...,E. Strongly agree,E. Strongly agree,D. Agree,E. Strongly agree,D. Agree,E. Strongly agree,I learnt about values and thier importance in ...,"If I may say, all things were well organised a...",BPZ_F5EG,NaN
411,BPZ_21,7,08/07/2026 15:25:04,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_28_0001.pdf,#3 XWEK,Meldon Achieng,7981,NaN,...,E. Strongly agree,D. Agree,D. Agree,D. Agree,E. Strongly agree,E. Strongly agree,I learnt how I can Identify a problem others a...,"To make the sessions better, you should have t...",BPZ_F5EG,NaN
412,BPZ_40,7,08/07/2026 15:25:03,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_4_0001.pdf,#3 XWEK,Gravin Solomon,8146,NaN,...,D. Agree,D. Agree,C. Not sure,D. Agree,D. Agree,D. Agree,I have learn how to solve problems in real lif...,come in time so that the session can end also ...,BPZ_F5EG,NaN
418,BPZ_29,7,08/07/2026 15:24:51,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_7_0001.pdf,#3 XWEK,Benish Akinyi,8128,NaN,...,C. Not sure,D. Agree,D. Agree,C. Not sure,D. Agree,D. Agree,About Gratitude.,That we should be responding questions and giv...,BPZ_F5EG,NaN
420,BPZ_22,7,08/07/2026 15:24:32,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_28_0001.pdf,#3 XWEK,Michelle Adhiambo,8104,NaN,...,E. Strongly agree,E. Strongly agree,D. Agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,I practised / learned how to handle or manage ...,What should be changed is like me the person w...,BPZ_F5EG,NaN
422,BPZ_39,7,08/07/2026 15:24:29,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_4_0001.pdf,#3 XWEK,Elisha Odhiambo,8044,NaN,...,E. Strongly agree,E. Strongly agree,A. Strongly disagree,E. Strongly agree,E. Strongly agree,E. Strongly agree,I learned how to face challenges issues and ho...,The student should be encourage to be open and...,BPZ_F5EG,NaN
428,BPZ_30,7,08/07/2026 15:24:20,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,LELAMIXEDSEC ONDARY_LMS_7_0001.pdf,#3 XWEK,Ashley Odhiambo,7984,NaN,...,E. Strongly agree,E. Strongly agree,A. Strongly disagree,E. Strongly agree,D. Agree,D. Agree,How to Show gratitude,need some we should be provided with some gifts,BPZ_F5EG,NaN

In [97]:
# 3. admission number mismatches (compared PER SCHOOL)
def _norm_school(df, col='School Name'):
    df = df.copy()
    df['_school_key'] = df[col].astype(str).str.strip().str.upper()
    return df

def find_adm_mismatches(df, reference_df):
    df_n = _norm_school(df)
    ref_n = _norm_school(reference_df)[['_school_key', 'Admission number']].drop_duplicates()

    merged = df_n.merge(
        ref_n,
        on=['_school_key', 'Admission number'],
        how='left',
        indicator=True
    )
    mismatches = merged[merged['_merge'] == 'left_only'].drop(columns=['_merge', '_school_key'])
    return mismatches

# admission numbers not found in prefill data, checked within the same school
baseline_adm_mismatches = find_adm_mismatches(baseline, prefill)
endline_adm_mismatches = find_adm_mismatches(endline, prefill)

# values in baseline but not in endline, per school
baseline_endline_mismatches = find_adm_mismatches(baseline, endline)

# values in endline but not in baseline, per school
endline_baseline_mismatches = find_adm_mismatches(endline, baseline)

endline_baseline_mismatches

,#,Pages,Uploaded (UTC),Link,Notes,Filename(s),Version,Student Name,Admission number,Shamiri ID,...,10. The sessions made me think about my own life in a useful way.,11. The sessions gave me ideas for handling challenges in my life.,12. I used something from the sessions outside the group.,13. I found the sessions useful.,14. I would recommend these sessions to another student.,15. I knew how to ask for extra support if I needed it.,What was the most useful thing you learned or practiced in the sessions?,What should be changed to make the sessions better for students?,Print Batch Nº,Tag
479,NV4_22,7,03/07/2026 15:10:58,https://www.papersurvey.io/app/surveys/kisumu-...,Not student who filled base line\n,STIGNATIUSLOYOLAMAGADISECONDARYSCHOOL_SILMS_2_...,#3 XWEK,Rosalia Adongo,5306,NaN,...,E. Strongly agree,E. Strongly agree,E. Strongly agree,E. Strongly agree,C. Not sure,C. Not sure,Value. I learnt about value and I practiced th...,to understand others and work as a teamwork Re...,NV4_PEYF,NaN
497,FIZ_4,7,10/06/2026 14:59:14,https://www.papersurvey.io/app/surveys/kisumu-...,NaN,AHEROGIRLSSECONDARYSCHOOL_AGS_5_0001.pdf,#3 XWEK,Jane Yvonne,11695,NaN,...,E. Strongly agree,E. Strongly agree,B. Disagree,E. Strongly agree,C. Not sure,E. Strongly agree,We need to be Confidence and have alot of cour...,Our time should be added inorder to understand...,FIZ_GRML,NaN